### ISSUE TITLE
Firmware MC60CAR01A10

### ISSUE THREAD

**Issue by glaucopgomes** [ngohaibac/Quectel_MC60_OpenCPU#1]
Where I can download the MC60CAR01A10 firmware?

**Comment by bacnh85** [comment]
Hi Glaucopgomes,

You should be able to get the FW from your respective distributor or local FAE. Where is your location ?

**Comment by bacnh85** [comment]
I do include the FW image in [the SDK repo](https://github.com/ngohaibac/Quectel_MC60_VSCode_SDK)
