### ISSUE TITLE
Facing issue with Windows 10 GCC

### ISSUE THREAD

**Issue by chandankumar1** [ngohaibac/Quectel_MC60_OpenCPU#2]
Sir, Check this link for detailed information I had putted in quectel forum

**Comment by bacnh85** [comment]
Hi Chandankumar1,

Pls advise the link ?

**Comment by chandankumar1** [comment]
Check this if it solves your problem:

https://forums.quectel.com/t/mc60-problem-with-flashing-firmware/2220/5

**Comment by bacnh85** [comment]
Hi chandankumar1,

Thanks for your info.
